---
title: "Notes and other text"
format: docx
editor: visual
---

### Notes and other text (for possible use in manuscript)

Science (impact factor = 63.714)

-   Research articles

    -   Present a major advance.

    -   Up to approximately 4500 words, including references, notes and captions.
        Corresponds to approximately 5 printed pages in journal (approxiumately 11 manuscript pages).

    -   Up to 6 figures or tables, and about 40 references.

-   Reports

    -   New research results of broad significance.

    -   Up to \~2500 words, including references, notes and captions.
        Corresponds to approximately 3 printed pages in journal (approximately 6 manuscript pages).

    -   Up to 4 figures or tables, and about 30 references.

Nature (impact factor = 69.8)

-   Articles

    -   Original reports whose conclusions represent a substantial advance in understanding of an important problem and have immediate, far-reaching implications.

    -   Biological sciences papers do not normally exceed 8 pages.
        This would be approximately 4300 words and 5-6 modest display items.

    -   This [article](https://www.nature.com/articles/s41586-022-04824-9) provides a potentially useful (e.g., recent) example of formatting and structure for a paper focused on ecology/evolution

PNAS (impact factor = 12.77)

-   Research reports

    -   Original research of exceptional importance.

    -   Preferred length is 6 pages, but up to 12 pages is allowed.
        6 page article is approximately 4,000 words, 50 references, and 4 medium-size figures or tables.

Nature Communications (impact factor = 17.694)

-   Article

    -   Papers published by the journal represent important advances of significance to specialists within each field.
        Open access.

    -   The main text (not including abstract, Methods, References and figure legends) is limited to 5,000 words.
        The maximum title length is 15 words.

Science Advances (impact factor = 14.957)

-   Publishes impactful research papers and reviews in any area of science.
    Journal extends the capacity of *Science* magazine to identify and promote significant advances in science and engineering.
    Open access.

-   Research article

    -   Should present a major advance.

    -   Articles can be short of long format, up to 15,000 words, with up to 10 figures and/or tables.

### Other introduction material for quick reference

P5:

we show using amphibian-pathogen system to demonstrate that resistance first demonstrate that first document evidence of strong selection in host populations that are persisting with a deadly fungal pathogen, indicative that evolutionary rescue in response to previous pathogen invasion may have occurred.
We then repeatedly translocate these "rescued" populations to non-natal habitats on the landscape and use longitudinal surveys, mark-recapture analysis, and population modeling to demonstrate that "rescued" populations recover and persist across a landscape of disease.
Thus, natural selection combined with translocations promotes the recovery of a species on the brink of disease-induced extinction.
These results may have broad implications for the many species worldwide that are threatened with extinction by the emergence of novel diseases.

Host evolution and population persistence/recovery

-   Species recovery in the face of severe disease (population growth rate \> 1 ) will depend on the ability of a species to move or change.

-   Despite several mechanisms by which recovery could occur (dispersal, evolution, phenotypic plasticity), population recovery following severe disease-induced declines has rarely (?) been documented in wildlife populations (Rabbits and myxomatosis in Australia, rabbits and hemorrhagic disease in AU (Mutze et al. 2015); trout and whirling disease: Miller and Vincent (2008); frogs in Australia, Central America, Sierra Nevada; sea stars: Moritsch and Raimondi 2018, other examples?
    Restrict to species of conservation concern?)
    .

-   Given the urgent need not to not only increase the size of remnant populations, but also reestablish extirpated populations, methods are critically needed by which the recovery of populations can be leveraged to facilitate landscape-scale recovery in the presence of ongoing disease.
    For example, the disease-caused decline of a wildlife species might ideally be followed by the eventual recovery of remnant populations via evolutionary rescue.
    These populations could then be used as sources of resistant individuals to reestablish populations extirpated following disease emergence (Mendelson et al. 2019, Joseph and Knapp 2018).

Population reestablishment using reintroduction of resistant hosts

-   "Rescued" populations provide a source of animals from which to repatriate extirpated populations and disentangle the effects of the local environment and genetics on host recoveries.

-   For rescued populations to contribute to landscape-scale species recovery, the fitness benefits gained through selection should manifest beyond the natal environment, allowing for the long-term growth and persistence of incipient populations in novel environmental conditions.

-   In this study, we first document evidence of strong selection in host populations that are persisting with a deadly fungal pathogen, indicative that evolutionary rescue in response to previous pathogen invasion may have occurred.
    We then repeatedly translocate these "rescued" populations to non-natal habitats on the landscape and use longitudinal surveys, mark-recapture analysis, and population modeling to demonstrate that "rescued" populations recover and persist across a landscape of disease.
    Thus, natural selection combined with translocations promotes the recovery of a species on the brink of disease-induced extinction.
    These results may have broad implications for the many species worldwide that are threatened with extinction by the emergence of novel diseases.

Description of MYL frog species complex, impacts of Bd, and evidence of recent recovery.

<!--# I'm not sure the following text still makes sense to include. If we de-emphasize evolutionary rescue, it seems a stretch to use it as the overarching framework for the paper. The following is my best attempt at doing so. I've left the additional text on evolutionary rescue below for use elsewhere in the manuscript. -->

We hypothesize that MYL frogs are recovering due to evolutionary rescue, that the resistant animals in these populations could be used successfully in translocations to reestablish extirpated populations, and that reestablished populations would have a relatively high probability of long-term persistence.
These hypotheses generate the following expectations:

-   Differences in allele frequencies exist between Bd-naive and recovering populations

-   Shared selective response across recovering populations

-   Changes in population growth rate due to evolution extend beyond the natal environment

-   In populations established via translocation of frogs from recovering populations, Bd load is not an important predictor of post-translocation frog survival (in contrast to important relationship between Bd load and frog survival during Bd-caused epizootics)

-   Population viability: Yearly population growth rate of translocated populations in similar environments to the natal environment should be greater than 1, indicating the capacity of the selected frogs to recover in the presence of the pathogen.

Then show how each result is consistent with those expectations.

<!--# Extra ER text for use in manuscript -->

-   "Evolutionary rescue" describes adaptation that occurs quickly enough to prevent extinction due to maladaptation to a new environment (Carlson et al. 2014), can reverse ongoing declines in some species (Golas et al. 2021; Searle et al. 2021).

-   ER has been proposed as a mechanism of recovery in wildlife populations decimated by disease (Epstein et al. 2016, Schiebelhut et al. 2018).
    This is despite the fact that when environmental change is rapid (e.g., arrival of a novel disease), the initial level of population maladaptation will be large, leaving little time for adaptive evolution to restore positive growth: Gomulkiewicz and Holt (1995), Bell and Gonzalez (2009), Lindsey et al. (2013).

    -   Tasmanian devils: Epstein et al. (2016), Wells et al., Ecology (2019)

    -   Frogs in Australia: Grogan et al. (2018), McKnight et al. (2020), Newell et al. (2013), Scheele et al., (2014)

    -   Frogs in Panama: Voyles et al. (2018)

    -   Frogs in the Sierra Nevada: Knapp et al. (2016) @knapp2016

    -   Sea Star Wasting Disease: Menge et al., Plos One (2016), Schiebelhut et al.
        PNAS (2018)

    -   White-nose syndrome: Gignoux-Wolfsohn et al. (2021) Molecular ecology.
